### ISSUE TITLE
Mention that pre-existing branch gh-pages is required

### ISSUE THREAD

**Issue by tschaffter** [ga4gh/gh-openapi-docs#41]
First time working with GH pages :)

## First attempt

When following the README instructions, I got the following error:

```
$ npx gh-openapi-docs
...
Preparing docs for API spec at 'openapi/openapi.yaml' (first-draft)
Cloning 'gh-pages' branch into '/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/.ghpages-tmp'
Cloning into '.'...
warning: Could not find remote branch gh-pages to clone.
fatal: Remote branch gh-pages not found in upstream origin
cp: no such file or directory: preview
Branch folder:
/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/preview/first-draft
Spec location:
/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/openapi/openapi.yaml

Bundling API spec...
Storing to:
/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/preview/first-draft/openapi.json
bundling openapi/openapi.yaml...
📦 Created a bundle for openapi/openapi.yaml at /home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/preview/first-draft/openapi.json in 15ms.
bundling openapi/openapi.yaml...
📦 Created a bundle for openapi/openapi.yaml at /home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/preview/first-draft/openapi.yaml in 18ms.
Generating OpenAPI docs index at '/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/preview/first-draft/docs/index.html'
Prerendering docs

🎉 bundled successfully in: /home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/preview/first-draft/docs/index.html (1019 KiB) [⏱ 0.198s]
OpenAPI docs folder contents:
index.html

Done (in 1s.)
```

### Notes

- The first fatal error is because I didn't have a branch `gh-pages` on remote. The README can mention that having this branch is a requirement before running `npx gh-openapi-docs`. Here is how I create this branch:

```
$ git checkout --orphan gh-pages

# preview files to be deleted
$ git rm -rf --dry-run .
# actually delete the files
$ git rm -rf .
# Create a commit to leave the limbo of the orphan branch and push to origin
touch README.md
git add README.md
git commit -m 'Initial gh-pages commit'
git push --set-upstream origin gh-pages
```

- The above logs ends with `Done (in 1s.)` despite getting a fatal error previously. This gives the impression that that the command completed successfully (I haven't checked the output of `echo $?` to see if the command returned a 0 = success).

## Second attempt

I know have the branch `gh-pages` on origin with a single file called `README.md`. I run again the following command:

```
$ npx gh-openapi-docs
...
Preparing docs for API spec at '' (gh-pages)
Cloning 'gh-pages' branch into '/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/.ghpages-tmp'
Cloning into '.'...
cp: no such file or directory: preview
Branch folder:
/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/preview/gh-pages
Spec location:
/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas
cp: omitting directory '/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas'

Bundling API spec...
Storing to:
/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/preview/gh-pages/openapi.json
error: missing required argument `entrypoints`.
error: missing required argument `entrypoints`.
Generating OpenAPI docs index at '/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/preview/gh-pages/docs/index.html'
Error: Error opening file "/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/preview/gh-pages/openapi.yaml"
ENOENT: no such file or directory, open '/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/preview/gh-pages/openapi.yaml'
    at ReadFileContext.callback (/home/tschaffter/.npm-packages/lib/node_modules/redoc-cli/node_modules/json-schema-ref-parser/lib/resolvers/file.js:51:20)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13)

Error: ENOENT: no such file or directory, open '/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/preview/gh-pages/openapi.yaml'
Empty open api docs folder contents
Done (in 1s.)
$ echo $?
0
```

### Notes

- Despite the errors, the command returns a success status (0)
- The content of my GH repo has been generated using the command `npx create-openapi-repo` (version 3.1.1). Because this repo `gh-openapi-docs` uses work from Redocly, who also provides the package `create-openapi-repo`, it would be great if `gh-openapi-docs` supports the initial file openapi/openapi.yml

I can further break down this ticket into individual issue based on the feedback received. Thanks!

**Comment by tschaffter** [comment]
The log currently show this message if the branch `gh-pages` does not exist:

> warning: Could not find remote branch gh-pages to clone.
fatal: Remote branch gh-pages not found in upstream origin

I gained experience working with gh-pages since I opened this ticket. I think that the current error message is OK and that there is plenty of documentation out there on how to create the branch `gh-pages`.
