### ISSUE TITLE
Return error code when an error occurs

### ISSUE THREAD

**Issue by tschaffter** [ga4gh/gh-openapi-docs#42]
The following command reports fatal issues but the code returns indicates success (0). Instead, the command should return 1 or other non-zero values to distinguish different error codes.

```
$ npx gh-openapi-docs
...
Preparing docs for API spec at '' (gh-pages)
Cloning 'gh-pages' branch into '/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/.ghpages-tmp'
Cloning into '.'...
cp: no such file or directory: preview
Branch folder:
/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/preview/gh-pages
Spec location:
/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas
cp: omitting directory '/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas'

Bundling API spec...
Storing to:
/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/preview/gh-pages/openapi.json
error: missing required argument `entrypoints`.
error: missing required argument `entrypoints`.
Generating OpenAPI docs index at '/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/preview/gh-pages/docs/index.html'
Error: Error opening file "/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/preview/gh-pages/openapi.yaml"
ENOENT: no such file or directory, open '/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/preview/gh-pages/openapi.yaml'
    at ReadFileContext.callback (/home/tschaffter/.npm-packages/lib/node_modules/redoc-cli/node_modules/json-schema-ref-parser/lib/resolvers/file.js:51:20)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13)

Error: ENOENT: no such file or directory, open '/home/tschaffter/persist/dev/nlp-sandbox-data-node-data-schemas/preview/gh-pages/openapi.yaml'
Empty open api docs folder contents
Done (in 1s.)
$ echo $?
0
```

**Comment by tschaffter** [comment]
The above error was initially reported in #41

**Comment by tschaffter** [comment]
I can no longer reproduce this error. I may have used an older version of `gh-openapi-docs` (0.1.8?). This is supported by the fact that the layout of the logs shown above does not match the layout of the log in version 0.2.1. Unfortunately I forgot to specify the version used when creating this ticket.
